# Generated by Django 5.2.7 on 2025-11-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'ADMIN'), ('cajero', 'CAJERO'), ('mesero', 'MESERO')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
