# Generated by Django 5.2.7 on 2025-10-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Nom_usuario', models.CharField(max_length=50)),
                ('Cargo', models.CharField(max_length=30)),
                ('Contrasenia', models.IntegerField(max_length=4)),
            ],
        ),
    ]
