# Generated by Django 5.2.7 on 2025-10-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('num_documento', models.IntegerField()),
                ('telefono', models.IntegerField(max_length=10)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
    ]
